version: '3'
services:
  nginx:
    image: nginx:1.25
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-1
      # - backend-2

  adminer:
    image: adminer:4-standalone
    ports:
      - '4001:8080' # Expose Adminer on port 8080
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '4002:3306' #HOST PORT:CONTAINER PORT (OUTSIDE:INSIDE)
    environment:
      - MYSQL_DATABASE=basic_laundromat #mysql database name
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql

  backend-1:
    # image: xxxxxx:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5001:3000' #HOST PORT:CONTAINER PORT (OUTSIDE:INSIDE) [Default: 3000]
    volumes:
      - ./backend/config.js:/app/config.js
    environment:
      - DB_CONNECTION_LIMIT=10
      - DB_HOST=host.docker.internal #mysql HOST 
      - DB_PORT=4002 #mysql HOST PORT [Default: 3306]
      - DB_USER=admin #mysql username (Permission: Read/Write database)
      - DB_PASSWORD=1234 #mysql password
      - DB_DATABASE=basic_laundromat #mysql database name
      - LINE_CHANNEL_ACCESS_TOKEN=O8sXKFqYykzebR47FuKiGbfmkacA9gz/taffAVmz+XpfxLSpJu/+SYZx6FCwUk57NpdJNj/U8lycHLetTGbB6axesr2GLdFEl4NJ9NNPMj45toX6qFDlLHaw16oXGZxwx9QLfQZSyR+uJPZdfKeDpgdB04t89/1O/w1cDnyilFU=
    restart: unless-stopped

  # backend-2:
  #   # image: xxxxxx:1.0
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5002:3000' #HOST PORT:CONTAINER PORT (OUTSIDE:INSIDE) [Default: 3000]
  #   volumes:
  #     - ./backend/config.js:/app/config.js
  #   environment:
  #     - DB_CONNECTION_LIMIT=10
  #     - DB_HOST=host.docker.internal #mysql HOST 
  #     - DB_PORT=4002 #mysql HOST PORT [Default: 3306]
  #     - DB_USER=admin #mysql username (Permission: Read/Write database)
  #     - DB_PASSWORD=1234 #mysql password
  #     - DB_DATABASE=basic_laundromat #mysql database name
  #     - LINE_CHANNEL_ACCESS_TOKEN=O8sXKFqYykzebR47FuKiGbfmkacA9gz/taffAVmz+XpfxLSpJu/+SYZx6FCwUk57NpdJNj/U8lycHLetTGbB6axesr2GLdFEl4NJ9NNPMj45toX6qFDlLHaw16oXGZxwx9QLfQZSyR+uJPZdfKeDpgdB04t89/1O/w1cDnyilFU=
  #   restart: unless-stopped

  frontend:
    # image: xxxxxx:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80' #HOST PORT:CONTAINER PORT (OUTSIDE:INSIDE) [Default: 80]
    environment:
      - REACT_APP_API_PATH=localhost:4000 #backend HOST PORT
    restart: unless-stopped #AUTO RESTART CONTAINER

volumes:
  mysql-volume:
